# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: "https"
  url: "dev-dataspaces.dit.upm.es"
  port: "1500"

# ==========================
# CONFIG
# ==========================

hosts_config:
  http: *http_host
  grpc: null
  graphql: null

connection_config:
  is_local: false
  is_tls_enabled: true

db_config:
  db_type: Postgres
  url: "heimdall-db"
  port: "5432"

wallet_config:
  api:
    protocol: "https"
    url: "wallet.demo.walt.id"
    port: null
  id: null

did_config:
  did: "did:jwk:eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiJtN3RpeFY2U2Q5MTJyZmk1ME10Y1FPYWJHZnVrMGhtNEZ4ZUtaTnV1OFNuMUh2WGFya0FUd2M2VzRSZ1FzVnA0UVlMdGRFSkpmQ2IxU0U2UDN4UXM3N3BNV0kzMzhOYk9ES2g0OEFOLUdIdjN0V3p4b3NmamV5aDRSTHB4bG00d1ZDWS1ZXzBSYmJCRzBnRUh5cmJ6SHhmU2NiZ2RMdnlGX2lab0ZIVWNnOHZCSERxVU5KblhESG5tcEpIRmlfYV84UTZuWUdka0lqVXdxWnRWbzB6ZWV0aVp3TTkwN05zZHhQYzN2b0ZqQ2Q1a3dacUtiMms4ZFl0bDhCLXUwdVBBcUFpRFJjYjloeG9QWUdUVmtJN1Nuc0hrekFsOHFOWFBKN1FBcTNxT2t1Y1RpbldYd3ltSTNOY3p2dzBtVDVQenpDNm5fcGRaQy1sUXo3WnZfblZXUXcifQ"
  type: Jwk
  did_web_options: null
  #    domain: "CHANGE_ME"
  #    path: null

role: DataSpaceAuthority

api_config:
  version: "v1"
  openapi_path: "./static/specs/openapi/openapi.json"

vc_config:
  vc_model: JwtVc
  w3c_data_model: V2

issue_config:
  dataspace_id: "RainbowDataspace"
  federated_catalog_uri: "http://uri_to_federated_catalog"

verify_req_config:
  is_cert_allowed: true
  vcs_requested: [ ]

is_react: true