host:
  protocol: http
  url: 127.0.0.1
  port: 1500

database_config:
  type: Postgres
  url: 127.0.0.1
  port: 1450
#  user: ds_authority
#  password: ds_authority
#  name: ds_authority

wallet_config:
  api_protocol: http
  api_url: 127.0.0.1
  api_port: 7001
#  type: email
#  name: RainbowAuthority
#  email: RainbowAuthority@rainbow.com
#  password: rainbow
  id: null

role: LegalAuthority

#keys_path: static/certificates/
is_local: true

api:
  version: v1
  openapi_path: static/specs/openapi/openapi.json

stuff_to_issue:
  vc_model: JwtVc
  w3c_data_model: V1
  dataspace_id: null
  did: "did:jwk:eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiJ4T0F3WlpkQ3AwQ0dCQV9tMVVHR1VXcEM5THJlcmJjbDMxblJoZThzNzd6R204aXA3YUgtUW5NNUNLbEo1YXlvUDhKTV9rLWhVQ0V2Q09qNWw5VmNhN0RfNTdRMjRJUEtHN0dQSGdnYzZ5bGxwZFlnSkVlY2xUcXJGcjdGUFBxcThDQzY1WVpfS1hGY3ByOHJGRVFEUGtkc3gzbU1qTkYzQUpNNzBpaEItdGtOOWxxcHZLb0h6MzJRaHRybVhFY2t1X1NtVFlFTU9GVU0xd0I1TE4xNmN4ZzIxZXYwMnZGdlVCYmdWZENTNHZocjNHNlNMM2dPZXVzd3BZaTZtTTZ6clloY3lkaDJaRjZCUEZVMS1NNk9tcENGRnd6SFVWNTdqMHJMLUR0OU1Ja1FUWmxXam5kcVVOZG1Ecnlyd0E1OU8zS1lWYWY5cmUwdW9QS3ZGUmRmY3cifQ"
  federated_catalog_uri: null

requirements_to_verify:
  is_cert_allowed: true
  vcs_requested: []