# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: "http"
  url: "127.0.0.1"
  port: "1500"

# ==========================
# CONFIG
# ==========================

hosts:
  http: *http_host
  grpc: null
  graphql: null

is_local: true

db_config:
  db_type: Postgres
  url: "127.0.0.1"
  port: "1450"

wallet_config:
  api:
    protocol: "https"
    url: "wallet.demo.walt.id"
    port: null
  id: null

did_config:
  did: "did:jwk:eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiJ4T0F3WlpkQ3AwQ0dCQV9tMVVHR1VXcEM5THJlcmJjbDMxblJoZThzNzd6R204aXA3YUgtUW5NNUNLbEo1YXlvUDhKTV9rLWhVQ0V2Q09qNWw5VmNhN0RfNTdRMjRJUEtHN0dQSGdnYzZ5bGxwZFlnSkVlY2xUcXJGcjdGUFBxcThDQzY1WVpfS1hGY3ByOHJGRVFEUGtkc3gzbU1qTkYzQUpNNzBpaEItdGtOOWxxcHZLb0h6MzJRaHRybVhFY2t1X1NtVFlFTU9GVU0xd0I1TE4xNmN4ZzIxZXYwMnZGdlVCYmdWZENTNHZocjNHNlNMM2dPZXVzd3BZaTZtTTZ6clloY3lkaDJaRjZCUEZVMS1NNk9tcENGRnd6SFVWNTdqMHJMLUR0OU1Ja1FUWmxXam5kcVVOZG1Ecnlyd0E1OU8zS1lWYWY5cmUwdW9QS3ZGUmRmY3cifQ" 
  type: Jwk
  did_web_options: null
#    domain: "CHANGE_ME"
#    path: null
  
role: LegalAuthority

api:
  version: "v1"
  openapi_path: "static/specs/openapi/openapi.json"

stuff_to_issue:
  vc_model: JwtVc
  w3c_data_model: V1
  dataspace_id: null
  federated_catalog_uri: null

requirements_to_verify:
  is_cert_allowed: true
  vcs_requested: []